# Generated by Django 3.0.3 on 2020-03-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0003_auto_20200304_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zform',
            name='date_pub_forms',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата сообщения'),
        ),
    ]
