# Generated by Django 3.0.3 on 2020-03-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0004_auto_20200304_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('subscribe_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Подписчики',
                'db_table': 'Подпичсики',
            },
        ),
    ]
