# Generated by Django 3.0.3 on 2020-03-19 10:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0005_subscribeform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribeForm',
        ),
        migrations.DeleteModel(
            name='zForm',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
