# Generated by Django 3.0.3 on 2020-03-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0006_auto_20200319_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
