# Generated by Django 3.0.3 on 2020-03-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0007_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
