# Generated by Django 3.0.3 on 2020-03-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0009_auto_20200319_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
